// biome-ignore assist/source/organizeImports: <Falso positivo do Biome>
import type { Knex } from "knex";
import { randomUUID } from "node:crypto";

export async function seed(knex: Knex): Promise<void> {
  await knex("properties").del();

  await knex("properties").insert([
    {
      id: randomUUID(),
      name: "Studio na Faria Lima",
      address: "R. Tavares Cabral, 61 - Pinheiros, São Paulo - SP",
      total_value: 80000000,
      rent_value: 350000,
      condo_value: 60000,
      tax_value: 12000,
      number_of_rooms: 1,
      number_of_bathrooms: 1,
      garage_slots: 1,
      are_pets_allowed: true,
      is_next_to_subway: true,
      is_active: true,
      is_sale: true,
      is_rent: true,
      is_furnished: false,
      size: 23,
      latitude: "-23.573880",
      longitude: "-46.691682",
      property_type: "STUDIO",
      description: "Studio moderno e bem localizado.",
    },
    {
      id: randomUUID(),
      name: "Casa de Esquina no Centro",
      address: "Centro, São Manuel - SP",
      total_value: 45000000,
      rent_value: 0,
      condo_value: 0,
      tax_value: 80000,
      number_of_rooms: 3,
      number_of_bathrooms: 2,
      garage_slots: 2,
      are_pets_allowed: true,
      is_next_to_subway: false,
      is_active: true,
      is_sale: true,
      is_rent: false,
      is_furnished: false,
      size: 150,
      latitude: "-22.7300",
      longitude: "-48.5700",
      property_type: "HOUSE",
      description: "Ampla casa no centro, excelente para família grande.",
    },
    {
      id: randomUUID(),
      name: "Apartamento Universitário",
      address: "Vila Universitária, Bauru - SP (Próx. UNISAGRADO)",
      total_value: 20000000,
      rent_value: 120000,
      condo_value: 20000,
      tax_value: 5000,
      number_of_rooms: 2,
      number_of_bathrooms: 1,
      garage_slots: 1,
      are_pets_allowed: false,
      is_next_to_subway: false,
      is_active: true,
      is_sale: false,
      is_rent: true,
      is_furnished: true,
      size: 55,
      latitude: "-22.3250",
      longitude: "-49.0600",
      property_type: "APARTMENT",
      description: "Todo mobiliado, ideal para estudantes dividirem.",
    },
    {
      id: randomUUID(),
      name: "Sobrado com Quintal",
      address: "Bairro das Flores",
      total_value: 65000000,
      rent_value: 400000,
      condo_value: 0,
      tax_value: 150000,
      number_of_rooms: 4,
      number_of_bathrooms: 3,
      garage_slots: 3,
      are_pets_allowed: true,
      is_next_to_subway: false,
      is_active: true,
      is_sale: true,
      is_rent: true,
      is_furnished: false,
      size: 220,
      latitude: "-23.1000",
      longitude: "-46.1000",
      property_type: "TOWNHOUSE",
      description: "Sobrado com churrasqueira e espaço para 3 carros.",
    },
    {
      id: randomUUID(),
      name: "Cobertura de Luxo Duplex",
      address: "Av. Paulista, São Paulo - SP",
      total_value: 450000000,
      rent_value: 2500000,
      condo_value: 350000,
      tax_value: 450000,
      number_of_rooms: 5,
      number_of_bathrooms: 5,
      garage_slots: 4,
      are_pets_allowed: true,
      is_next_to_subway: true,
      is_active: true,
      is_sale: true,
      is_rent: true,
      is_furnished: true,
      size: 400,
      latitude: "-23.561684",
      longitude: "-46.655981",
      property_type: "APARTMENT",
      description: "Cobertura absurda com piscina privativa.",
    },
  ]);
}
